#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-or-later
#
# Entrypoint for the rootless piler image, based on jsuto/piler's docker/start.sh.
#
set -o errexit
set -o pipefail
set -o nounset

# piler.key, .my.cnf and the config files hold secrets.
umask 077

# Overridable for the offline tests.
CONFIG_DIR="${CONFIG_DIR:-/etc/piler}"
PILER_CONF="${CONFIG_DIR}/piler.conf"
PILER_KEY="${CONFIG_DIR}/piler.key"
PILER_PEM="${CONFIG_DIR}/piler.pem"
PILER_NGINX_CONF="${CONFIG_DIR}/piler-nginx.conf"
CONFIG_SITE_PHP="${CONFIG_DIR}/config-site.php"
PILER_MY_CNF="${CONFIG_DIR}/.my.cnf"
RT="${RT:-1}"
MEMCACHED_HOSTNAME="${MEMCACHED_HOSTNAME:-memcached}"
MYSQL_PORT="${MYSQL_PORT:-3306}"
MANTICORE_HOSTNAME="${MANTICORE_HOSTNAME:-manticore}"
MANTICORE_PORT="${MANTICORE_PORT:-9306}"
MANTICORE_PORT_READONLY="${MANTICORE_PORT_READONLY:-9307}"
MEMCACHED_PORT="${MEMCACHED_PORT:-11211}"
TMP_CONF_DIR="${TMP_CONF_DIR:-/tmp/piler-conf}"
PILER_USER="${PILER_USER:-piler}"
# Slash-free, so it needs no escaping as a sed address.
CONFIG_SITE_MARKER="# generated by entrypoint, do not edit below this line"
# Checked against the template to catch an upstream rename. mysqlport is left
# out: the template lacks it on purpose.
PILER_CONF_KEYS=(mysqlhost mysqluser mysqldb mysqlpwd hostid tls_enable sphxhost
                 sphxport rtindex mysqlsocket pidfile)

error() {
   echo "ERROR:" "$*" 1>&2
   exit 1
}

log() {
   echo "DEBUG:" "$*"
}

# sed -i renames over the target, which fails with "Device or resource busy" on
# a bind mount.
safe_sed() {
   local target="$1"
   shift

   local tmp
   tmp="$(mktemp)"
   sed "$@" "$target" > "$tmp"
   cat "$tmp" > "$target"
   rm -f "$tmp"
}

sed_replacement() {
   local delim="$1" s="$2"
   s="${s//\\/\\\\}"
   s="${s//&/\\&}"
   s="${s//"${delim}"/\\${delim}}"
   printf '%s' "$s"
}

# Appends the key when missing: sed cannot add a line.
conf_set() {
   local file="$1" key="$2" value="$3"

   if grep -q "^${key}=" "$file"; then
      safe_sed "$file" "s/${key}=.*/${key}=$(sed_replacement / "$value")/g"
      return
   fi

   if [[ -s "$file" && -n "$(tail -c1 "$file")" ]]; then
      printf '\n' >> "$file"
   fi
   printf '%s=%s\n' "$key" "$value" >> "$file"
}

php_single_quoted() {
   local s="$1"
   s="${s//\\/\\\\}"
   s="${s//\'/\\\'}"
   printf '%s' "$s"
}

# Unquoted, '#' starts a comment and a trailing space is trimmed.
my_cnf_value() {
   local s="$1"
   s="${s//\\/\\\\}"
   s="${s//\"/\\\"}"
   printf '"%s"' "$s"
}


pre_flight_check() {
   local var
   for var in PILER_HOSTNAME MYSQL_HOSTNAME MYSQL_DATABASE MYSQL_USER MYSQL_PASSWORD; do
      [[ -n "${!var:-}" ]] || error "Missing ${var} env variable"
   done

   # A newline aborts a sed mid-file, and command substitution eats a trailing one.
   for var in PILER_HOSTNAME MYSQL_HOSTNAME MYSQL_DATABASE MYSQL_USER \
              MYSQL_PASSWORD MANTICORE_HOSTNAME MEMCACHED_HOSTNAME; do
      [[ "${!var:-}" != *[$'\n\r\t']* ]] \
         || error "${var} must not contain a newline, carriage return or tab"
   done
   local port
   for port in MYSQL_PORT MANTICORE_PORT MANTICORE_PORT_READONLY MEMCACHED_PORT; do
      [[ "${!port}" =~ ^[1-9][0-9]{0,4}$ && "${!port}" -le 65535 ]] \
         || error "${port} must be a port number between 1 and 65535, got '${!port}'"
   done
   [[ "$RT" == "1" ]] || error "RT must be 1 (real-time mode), got RT='${RT}'. This image runs piler against an external manticore container with no local indexer binary, so any value other than 1 (including batch mode RT=0) is unsupported."
}

give_it_to_piler() {
   local f="$1"

   [[ -f "$f" ]] || error "${f} does not exist, aborting"

   chown "${PILER_USER}:${PILER_USER}" "$f"
   chmod 600 "$f"
}

make_certificate() {
   local f="$1"
   local crt="/tmp/1.cert"
   local SSL_CERT_DATA="/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"

   log "Making an ssl certificate"

   openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj "$SSL_CERT_DATA" -keyout "$f" -out "$crt" -sha256 2>/dev/null
   cat "$crt" >> "$f"
   rm -f "$crt"

   give_it_to_piler "$f"
}

make_piler_key() {
   local f="$1"

   log "Generating piler.key"

   dd if=/dev/urandom bs=56 count=1 of="$f" 2>/dev/null
   [[ $(stat -c '%s' "$f") -eq 56 ]] || error "could not read 56 bytes from /dev/urandom to ${f}"

   give_it_to_piler "$f"
}

write_piler_nginx_conf() {
   log "Writing ${PILER_NGINX_CONF}"

   cp "${TMP_CONF_DIR}/piler-nginx.conf.dist" "$PILER_NGINX_CONF"
   safe_sed "$PILER_NGINX_CONF" "s%PILER_HOST%$(sed_replacement % "$PILER_HOSTNAME")%"
}

fix_configs() {
   [[ -f "$PILER_KEY" ]] || make_piler_key "$PILER_KEY"
   [[ -f "$PILER_PEM" ]] || make_certificate "$PILER_PEM"

   # Also regenerate if an older template left it without a listen directive.
   if [[ ! -f "$PILER_NGINX_CONF" ]] || ! grep -q '^\s*listen\s' "$PILER_NGINX_CONF"; then
      write_piler_nginx_conf
   fi

   if [[ ! -f "$PILER_CONF" ]]; then
      cp "${TMP_CONF_DIR}/piler.conf.dist" "$PILER_CONF"
   fi

   log "Updating ${PILER_CONF}"

   # The template comes with the binary, the live file may be older.
   local key
   for key in "${PILER_CONF_KEYS[@]}"; do
      grep -q "^${key}=" "${TMP_CONF_DIR}/piler.conf.dist" \
         || error "no ${key}= line in ${TMP_CONF_DIR}/piler.conf.dist; piler renamed that key upstream, so this image would set one it ignores"
   done

   conf_set "$PILER_CONF" mysqlhost "$MYSQL_HOSTNAME"
   conf_set "$PILER_CONF" mysqlport "$MYSQL_PORT"
   conf_set "$PILER_CONF" mysqluser "$MYSQL_USER"
   conf_set "$PILER_CONF" mysqldb "$MYSQL_DATABASE"
   conf_set "$PILER_CONF" mysqlpwd "$MYSQL_PASSWORD"
   conf_set "$PILER_CONF" hostid "$PILER_HOSTNAME"
   conf_set "$PILER_CONF" tls_enable 1
   conf_set "$PILER_CONF" sphxhost "$MANTICORE_HOSTNAME"
   conf_set "$PILER_CONF" sphxport "$MANTICORE_PORT"
   conf_set "$PILER_CONF" rtindex "$RT"
   conf_set "$PILER_CONF" mysqlsocket ""
   conf_set "$PILER_CONF" pidfile /var/piler/run/piler.pid

   give_it_to_piler "$PILER_CONF"

   if [[ ! -f "$CONFIG_SITE_PHP" ]]; then
      log "Writing ${CONFIG_SITE_PHP}"

      cp "${TMP_CONF_DIR}/config-site.dist.php" "$CONFIG_SITE_PHP"

      safe_sed "$CONFIG_SITE_PHP" "s%HOSTNAME%$(sed_replacement % "$PILER_HOSTNAME")%"

      # A template without a trailing newline would swallow the marker line.
      if [[ -n "$(tail -c1 "$CONFIG_SITE_PHP")" ]]; then
         printf '\n' >> "$CONFIG_SITE_PHP"
      fi
   fi

   log "Updating ${CONFIG_SITE_PHP}"

   # piler's DSN has no port field, but PDO parses host:port.
   local db_host="${MYSQL_HOSTNAME}:${MYSQL_PORT}"

   # Rewritten every start. PHP keeps the last assignment, so it wins over the
   # template above the marker.
   safe_sed "$CONFIG_SITE_PHP" "/^${CONFIG_SITE_MARKER}\$/,\$d"

   {
      echo "$CONFIG_SITE_MARKER"
      echo "\$config['RT'] = 1;"
      echo "\$config['DB_HOSTNAME'] = '$(php_single_quoted "$db_host")';"
      echo "\$config['DB_DATABASE'] = '$(php_single_quoted "$MYSQL_DATABASE")';"
      echo "\$config['DB_USERNAME'] = '$(php_single_quoted "$MYSQL_USER")';"
      echo "\$config['DB_PASSWORD'] = '$(php_single_quoted "$MYSQL_PASSWORD")';"
      echo "\$memcached_server = ['$(php_single_quoted "$MEMCACHED_HOSTNAME")', ${MEMCACHED_PORT}];"
      echo "\$config['SPHINX_HOSTNAME'] = '$(php_single_quoted "$MANTICORE_HOSTNAME"):${MANTICORE_PORT}';"
      echo "\$config['SPHINX_HOSTNAME_READONLY'] = '$(php_single_quoted "$MANTICORE_HOSTNAME"):${MANTICORE_PORT_READONLY}';"
   } >> "$CONFIG_SITE_PHP"

   # Only when absent, so the module may set its own. RELOAD_COMMAND skips the
   # broken systemctl default (jsuto/piler#479): everything runs as piler.
   local setting key
   for setting in \
      "SPHINX_MAIN_INDEX|'piler1'" \
      "MEMCACHED_ENABLED|1" \
      "DECRYPT_BINARY|'/usr/bin/pilerget'" \
      "DECRYPT_ATTACHMENT_BINARY|'/usr/bin/pileraget'" \
      "PILER_BINARY|'/usr/sbin/piler'" \
      "RELOAD_COMMAND|'/etc/init.d/rc.piler reload'"; do
      key="${setting%%|*}"
      grep -q "config\['${key}'\]" "$CONFIG_SITE_PHP" \
         || echo "\$config['${key}'] = ${setting#*|};" >> "$CONFIG_SITE_PHP"
   done

   give_it_to_piler "$CONFIG_SITE_PHP"
}

wait_until_mysql_server_is_ready() {
   local attempts=0
   local max_attempts="${MYSQL_WAIT_MAX_ATTEMPTS:-60}"

   until mysql "--defaults-file=${PILER_MY_CNF}" <<< "show databases" >/dev/null 2>&1; do
      attempts=$((attempts + 1))
      if [[ "$attempts" -ge "$max_attempts" ]]; then
         error "${MYSQL_HOSTNAME} not ready after ${max_attempts} attempts, giving up"
      fi
      log "${MYSQL_HOSTNAME} is not ready (${attempts}/${max_attempts})"
      sleep 5
   done

   log "${MYSQL_HOSTNAME} is ready"
}

init_database() {
   local table
   local has_metadata_table=0

   wait_until_mysql_server_is_ready

   while read -r table; do
      if [[ "$table" == metadata ]]; then has_metadata_table=1; fi
   done < <(mysql "--defaults-file=${PILER_MY_CNF}" "$MYSQL_DATABASE" <<< 'show tables')

   if [[ $has_metadata_table -eq 0 ]]; then
      log "no metadata table, creating tables"

      mysql "--defaults-file=${PILER_MY_CNF}" "$MYSQL_DATABASE" < /usr/share/piler/db-mysql.sql
   else
      log "metadata table exists"
   fi
}

create_my_cnf_files() {
   # ssl = false: Ubuntu 26.04's client requires TLS, the mariadb container has none.
   local host user pass
   host="$(my_cnf_value "$MYSQL_HOSTNAME")"
   user="$(my_cnf_value "$MYSQL_USER")"
   pass="$(my_cnf_value "$MYSQL_PASSWORD")"

   printf "[client]\nhost = %s\nport = %s\nuser = %s\npassword = %s\nssl = false\n[mysqldump]\nhost = %s\nport = %s\nuser = %s\npassword = %s\nssl = false\n" \
      "$host" "$MYSQL_PORT" "$user" "$pass" "$host" "$MYSQL_PORT" "$user" "$pass" \
      > "$PILER_MY_CNF"

   give_it_to_piler "$PILER_MY_CNF"
}

# Sourced by the tests to get the functions without starting anything.
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
   pre_flight_check
   fix_configs
   create_my_cnf_files
   init_database

   exec "$@"
fi
