#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Connect to redis
rdb = agent.redis_connect()

providers = agent.list_service_providers(rdb, 'imap', 'tcp', {
    'module_uuid': data["mail_server"],
})

if providers:
    # Set the PROVIDER_IP (IPV4) environment variable to the host of the first provider
    agent.set_env("PROVIDER_IP", providers[0]["host"])
else:
    # If no provider is found, set the PROVIDER_IP to an empty string
    agent.set_env("PROVIDER_IP", "")

agent.set_env("RETENTION_DAYS", data["retention_days"])
