#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
set -e

exec 1>&2 # Redirect any output to the journal (stderr)

# If the control reaches this step, the service can be enabled and started

systemctl --user enable piler.service
# we need to list all the services to execute and wait after wait-after-piler script (90add-relay-rule expect smtp validation)
systemctl --user restart piler.service manticore-app.service  mariadb-app.service  memcached-app.service  piler-app.service
