#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# This script is used to start the import-email-to-piler.service
if [[ -f 'sync2pilerdone' ]]; then
    echo "## sync2pilerdone file is found, mail already migrated, exiting"
    exit 0
fi
systemctl --user start import-email-to-piler.service
