#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Read the piler configuration and expect for configured domains 
# else build again the configuration (this is useful for the first run)
if grep -q "\$domains = \[\];" piler_etc/config-site.php; then
    ../bin/expand-configuration
fi
