#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

tcp_ports = os.environ['TCP_PORTS'].split(',')
agent.set_env("TCP_PORT_ARCHIVE", tcp_ports[0])
agent.set_env("TCP_PORT_TRAEFIK", tcp_ports[1])


# Ignore exit code
