#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
set -e

# we need to restart the stack to wait after piler full restart
if systemctl --user is-active --quiet piler-app.service; then
    echo "Piler is active, restarting the stack"
    systemctl --user restart piler.service manticore-app.service  mariadb-app.service  memcached-app.service piler-app.service
fi
