#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
set -e

exec 1>&2 # Redirect any output to the journal (stderr)

systemctl --user try-restart piler.service
