#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
set -e
exec 1>&2 # Redirect any output to the journal (stderr)

if podman volume inspect piler_manticore > /dev/null 2>&1; then
    # remove the old index the change of sphinx version need to reindex the emails
    # needed for upgrade from 1.4.4 to 1.4.8 (ns8-piler 1.0.1)
    echo "Removing piler_manticore volume for manticore upgrade to 10.1.0"
    podman volume rm -f piler_manticore

    # reindex emails in background
    podman exec -d -w /var/piler/imap piler-app bash -c '
        exec >/proc/1/fd/1
        exec 2>/proc/1/fd/2
        echo "Reindexing emails now ..."
        reindex -a -p
        if [ $? -ne 0 ]; then
            echo "Reindexing failed"
            exit 1
        fi
        echo "Reindexing is finished"
    '
fi
