#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Remove traefik route

import os
import sys
import json
import agent
import agent.tasks

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

# Remove traefik route
response = agent.tasks.run(
    agent_id=default_traefik_id,
    action='delete-route',
    data={
        'instance': os.environ['MODULE_ID']
    },
)

# we want to remove the relay from the mail server
rdb = agent.redis_connect()
providers_old = agent.list_service_providers(rdb, 'imap', 'tcp', {
    'module_uuid': os.environ.get("MAIL_SERVER")
})
if providers_old:
    mail_id_old = providers_old[0]["module_id"]
    response = agent.tasks.run(f"module/{mail_id_old}", action='remove-relay-rule', data={
        "rule_subject": "archive@"+os.environ.get("TRAEFIK_HOST")})
    # we need to set bcc address for the mail server
    response = agent.tasks.run(f"module/{mail_id_old}", action='set-always-bcc', data={
        "bcc": ""
    })
