#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_HOST",
        "TRAEFIK_HTTP2HTTPS",
        "TRAEFIK_LETS_ENCRYPT",
        "MAIL_SERVER",
    ]:
    agent.set_env(evar, original_environment[evar])

tcp_ports = os.environ['TCP_PORTS'].split(',')
agent.set_env("TCP_PORT_ARCHIVE", tcp_ports[0])
agent.set_env("TCP_PORT_TRAEFIK", tcp_ports[1])
