#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_HOST",
        "TRAEFIK_HTTP2HTTPS",
        "TRAEFIK_LETS_ENCRYPT",
        "IMAP_HOST"
    ]:
    agent.set_env(evar, original_environment[evar])

# web uses the first one, archive uses the second random port
env_tcp_ports = os.environ["TCP_PORTS"].split(',')
tcp_port_web = env_tcp_ports[0]
tcp_port_archive = env_tcp_ports[1]

# Talk with agent using file descriptor.
# Setup configuration from user input.
agent.set_env("TCP_PORT_WEB", tcp_port_web )
agent.set_env("TCP_PORT_ARCHIVE", tcp_port_archive)

agent.dump_env()