#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

# open port in FW
tcp_port_archive = os.environ["TCP_PORT_ARCHIVE"]

agent.add_public_service(os.environ['MODULE_ID'], [
    tcp_port_archive +"/tcp", # external SMTP piler
])

# Ignore exit code